// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE2olXyogRWeH1aZYt0jg_vyXwaY4LCbg',
    appId: '1:278391735235:web:ed29da9c792f9faf503376',
    messagingSenderId: '278391735235',
    projectId: 'fir-multi-app-demo',
    authDomain: 'fir-multi-app-demo.firebaseapp.com',
    storageBucket: 'fir-multi-app-demo.appspot.com',
    measurementId: 'G-8FY91XDRHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmlLCeYaHIkjpFBwZ8b4yYw_t7i3e3rKs',
    appId: '1:278391735235:android:380eb68c47a5892a503376',
    messagingSenderId: '278391735235',
    projectId: 'fir-multi-app-demo',
    storageBucket: 'fir-multi-app-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcf9PcdE5M4EM-iy_ANmRq-2BgIAqI5sI',
    appId: '1:278391735235:ios:71807e7875f6b37b503376',
    messagingSenderId: '278391735235',
    projectId: 'fir-multi-app-demo',
    storageBucket: 'fir-multi-app-demo.appspot.com',
    iosClientId: '278391735235-2s0tbsla4gk01ov6lil26b8cm60pi7j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMultiAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcf9PcdE5M4EM-iy_ANmRq-2BgIAqI5sI',
    appId: '1:278391735235:ios:ea7ce6bfb1cf899e503376',
    messagingSenderId: '278391735235',
    projectId: 'fir-multi-app-demo',
    storageBucket: 'fir-multi-app-demo.appspot.com',
    iosClientId: '278391735235-j2tbj0h0ha4s6rj2sd8rsint5bbl7vpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMultiAppDemo.RunnerTests',
  );
}
